In [19]:
import torch ## import pytorch
import torch.nn as nn
import numpy as np ## import of numpy
#from torch.utils.tensorboard import SummaryWriter

In [18]:
## Vector 1D:
## Matrix 2D:
## Tensor ND: (1-N)
## A pytorch tensor (random)
vector = np.array([[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]])
print(vector.shape)


print(ten_n.shape)
ten = torch.tensor([1., 2., 3.]) ## 1D tensor
print(ten.shape)
print(ten.type())
a = torch.FloatTensor([[[1, 2, 3]]])
print(a.shape)


(2, 2, 3)


NameError: name 'ten_n' is not defined

In [12]:
## clear content of a tensor (without altering the tensor) (Functional, makes a copy
## of the tensor)
# b = torch.zeros_like(a) ## 
# print(a)
# print(b)
# print(a)
# print()
## clear content of a tensor (alter the tensor)
a.zero_()
print(a)
print(a)

NameError: name 'a' is not defined

In [13]:
## we make a numpy array
a_numpy = np.random.normal(loc=0, scale=1.0, size=(3,2)) ## create a random uniform distrib (mean=0, std=1.0 size=(3,2))

## convert it into pytorch tensor
a_tensor = torch.tensor(a_numpy, dtype=torch.float)
#print(a_tensor)
a = torch.randn((2,3))

In [217]:
## tensor operations
a = torch.tensor([1., 2., -3.])
print(a.sum()) ## sum all elements in the tensor
print(a)
print(a.mean()) ## ## get the mean of the tensor
print(a.mode()) ## get the mode of the tensor
print(a.median()) ## get the meadian of the tensor
print(a.abs()) ## get the abs of the tensor
#print(a.)

tensor(0.)
tensor([ 1.,  2., -3.])
tensor(0.)
torch.return_types.mode(
values=tensor(-3.),
indices=tensor(2))
tensor(1.)
tensor([1., 2., 3.])


In [218]:
## GPU tensors
print(a) ## this is a cpu tensor when you make it
print(a.device) ## to see what the device that tensor assigned to
print(a.to('cuda')) ## assign to the GPU
print(a.to('cuda').device)

tensor([ 1.,  2., -3.])
cpu
tensor([ 1.,  2., -3.], device='cuda:0')
cuda:0


In [219]:
## tensor gradients
v1 = torch.tensor([1.0, 2.0]) ## does not required gradient computation
v2 = torch.tensor([3.1, 1.0], requires_grad=True) ## require gradient computation

## operate on the tensors
v_sum = v1 + v2 ## computation graph step-1
v_res = (v_sum*2).sum() ## computation graph step-2
#print(v_sum)
#print(v_res)

## user made tensors are leafs in  a graph
## but intermediate operations are not
print(v1.is_leaf)
print(v_sum.is_leaf)

'''
with torch.no_grad():
    ## execute you model
'''
## are gradients required
#print(v1.requires_grad)
#print(v2.grad)

True
False


'\nwith torch.no_grad():\n    ## execute you model\n'

In [220]:
## NN blocks
import torch.nn as nn
linear_layer = nn.Linear(3, 5, bias=True) ## y = x(A)^T + b
print(linear_layer.state_dict())
weight = torch.randn((5, 3))
linear_layer.weight.data.fill_(weight)

## A weight matrix and b = biases
inp = torch.tensor([1, 2, 3], dtype=torch.float)
linear_layer(inp)

OrderedDict([('weight', tensor([[ 0.2511, -0.0676, -0.0525],
        [ 0.0820, -0.3997,  0.5529],
        [ 0.3400,  0.1264,  0.1481],
        [-0.0356, -0.5256,  0.2352],
        [ 0.3352, -0.1250,  0.1937]])), ('bias', tensor([-0.3236,  0.3611,  0.1582,  0.1286,  0.3971]))])


RuntimeError: fill_ only supports 0-dimension value tensor but got tensor with 2 dimensions.

In [183]:
## layer parameter
print(linear_layer.parameters()) ## return a generator that yields the layer parameter (A, b); A: 3x5 b: 3
for i in linear_layer.parameters():
    print(i)

<generator object Module.parameters at 0x7f5131541ba0>
Parameter containing:
tensor([[-0.0636, -0.1714,  0.5334],
        [-0.4526, -0.0075, -0.0849],
        [ 0.3653, -0.1952, -0.5339],
        [ 0.0509, -0.4912, -0.0707],
        [ 0.2531, -0.4524, -0.2112]], requires_grad=True)
Parameter containing:
tensor([0.5584, 0.2092, 0.4176, 0.3726, 0.2655], requires_grad=True)


In [184]:
## layer parameter
print(linear_layer.state_dict()) ## parameters and biases as a dictionary

OrderedDict([('weight', tensor([[-0.0636, -0.1714,  0.5334],
        [-0.4526, -0.0075, -0.0849],
        [ 0.3653, -0.1952, -0.5339],
        [ 0.0509, -0.4912, -0.0707],
        [ 0.2531, -0.4524, -0.2112]])), ('bias', tensor([0.5584, 0.2092, 0.4176, 0.3726, 0.2655]))])


In [189]:
## A simple ANN model
model = nn.Sequential( ### stack layers to make a neural network graph
    nn.Linear(2,5), ## first layer
    nn.ReLU(), ## first activation function
    nn.Linear(5,20),
    nn.ReLU(),
    nn.Linear(20,10),
    nn.ReLU(),
    nn.Dropout(p=0.3),
    nn.Softmax(dim=1) ## Softmax probability
)
model

Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=10, bias=True)
  (5): ReLU()
  (6): Dropout(p=0.3, inplace=False)
  (7): Softmax(dim=1)
)

In [193]:
inp = torch.FloatTensor([[1,2]]) ## dummy inputs
model(inp).shape ## call forward on the network

torch.Size([1, 10])

In [156]:
# ## model construction by subclassing
# class Model(nn.Module): ## nn.Module the parent class and class Model is the child class
#     ## initialize the model class
#     def __init__(self, input_shape, output_shape, drop=0.3):
#         super(Model, self).__init__()
#         '''
#         self.model_1 = nn.Sequential(
#                         nn.Linear(input_shape,5),
#                         nn.ReLU(),
#                         nn.Linear(5,20),
#                         nn.ReLU(),
#                         nn.Linear(20,5),
#                         )
#         self.model_2 = nn.Sequential(
#                         nn.Linear(input_shape,5),
#                         nn.ReLU(),
#                         nn.Linear(5,20),
#                         nn.ReLU(),
#                         nn.Linear(20,5),
#                         )
#         '''
#         #self.fc_1 = nn.Linear()
#     ## forward pass of the NN
#     ## execute the model with the inputs
#     def forward(self, x): ## x is the model input
#         return F.linear(2, 5)(x)
#         #return self.model_1(x) + self.model_2(x)
#         #return self.model(x) ## execute and get the output


In [20]:
## model construction by subclassing
class Model(nn.Module):
    def __init__(self, input_shape, output_shape, drop=0.3):
        super(Model, self).__init__()
        self.model = nn.Sequential(
                        nn.Linear(input_shape,5),
                        nn.ReLU(),
                        nn.Linear(5,20),
                        nn.ReLU(),
                        nn.Linear(20,output_shape),
                        #nn.ReLU(),
                        #nn.Dropout(p=0.3),
                        #nn.Softmax(dim=1)
                        )
    ## forward pass of the NN
    def forward(self, x):
        return self.model(x)


In [21]:
## construct the model
net = Model(2, 1) ## contruct the model object
inp = torch.FloatTensor([[2, 3]]) ## 1x2
print(inp.shape)
out = net(inp) ## call the model
#print(net)
print(out.shape)

torch.Size([1, 2])
torch.Size([1, 1])


In [22]:
optimizer = torch.optim.SGD(net.parameters(), lr=0.001)

In [23]:
## make some random data
inp_batch = torch.normal(0, 1, (1000, 2)) ## 1000x input_size training data ## (1000, c, h, w)
print(inp_batch.size())
tgt_batch = torch.normal(0, 1, (1000, 1)) # 1000x output_size training data ## (1000, cat or dog)

torch.Size([1000, 2])


In [24]:
#writer = SummaryWriter()
for e in range(10000): ## 
    epoch_loss = list()
    for i in range(0, inp_batch.shape[0], 10):
        inp = inp_batch[i:i+10] ## get the batches of data (10x2), (10x2)
        tgt = tgt_batch[i:i+10]## get the batches of data (10x1), (10x1)
        out = net(inp) ## call the model with the input batches
        #print(out.shape)
        optimizer.zero_grad() ## initialize the gradients for the new batch
        loss = nn.MSELoss()(out, tgt) ## compute the Mean Square Error Loss
        loss.backward() ## Backpropagate the loss gradients
        optimizer.step() ## update the neural network parameter using the optimizer
        epoch_loss.append(loss.item())
        #writer.add_scalar("error", loss.item())
    print(np.array(np.mean(epoch_loss)))
#writer.close()

    

79662037
0.93567088291049
0.9356694009900093
0.9357641416788102
0.9356085073947906
0.9356935553252697
0.9356047382950783
0.9357109233736992
0.9357283003628254
0.9356097076833249
0.9356378895044327
0.9356434515118599
0.9357337358593941
0.9356496964395046
0.9355632607638836
0.9357718655467033
0.9355629953742027
0.9356202192604541
0.9356119003891945
0.9356359621882439
0.9356990000605583
0.9355771526694298
0.9356330972909928
0.9356820087134838
0.9355535957217217
0.9355944633483887
0.9356013496220111
0.935600993335247
0.9355988848209381
0.9355808751285076
0.9356887006759643
0.9355555316805839
0.9355433973670005
0.9356751069426537
0.9355405279994011
0.9355336447060109
0.9355956986546516
0.9356931227445603
0.9355186213552952
0.9355014596879482
0.9355756866931916
0.9355295392870903
0.9356514038145543
0.9355037353932858
0.9355208170413971
0.9356468482315541
0.9355174168944359
0.9356091682612896
0.935480551123619
0.9355504953861237
0.9354934914410115
0.9356366369128227
0.9354556514322758
0.93563